import type { MenuCategory, Product } from "./types";

export const seedCategories = [
  ["che-quoc-dan-hamichee", "Chè Quốc Dân Hamichee", "3% 34%"],
  ["che-truyen-thong", "Chè Truyền Thống", "29% 88%"],
  ["che-ly", "Chè Ly", "46% 38%"],
  ["sua-chua", "Sữa Chua", "57% 43%"],
  ["tuoi-mat", "Tươi Mát", "56% 68%"],
  ["trung-nha", "Trứng Nhà", "56% 92%"],
  ["an-chill-cung-che", "Ăn Chill Cùng Chè", "70% 84%"],
  ["them-chut-ngon-hon", "Thêm Chút Ngon Hơn", "89% 51%"],
  ["the-gioi-hat-dac", "Thế Giới Hạt Đác", "91% 90%"],
] as const;

type SeedProduct = readonly [
  id: string,
  categoryId: string,
  name: string,
  price: number,
  featured?: boolean,
  variants?: ReadonlyArray<{ label: string; price: number }>,
];

export const seedProducts: readonly SeedProduct[] = [
  ["che-buoi","che-quoc-dan-hamichee","CHÈ BƯỞI",22000,true],
  ["che-thuong-hami","che-quoc-dan-hamichee","CHÈ \"THƯƠNG\" HAMI",28000,true],
  ["che-san-mochi-dua-non","che-quoc-dan-hamichee","CHÈ SẦN MOCHI DỪA NON",28000,true],
  ["che-mam-hami","che-quoc-dan-hamichee","CHÈ MÂM HAMI",89000,true],
  ["che-hat-dac-sau-rieng-hami","che-quoc-dan-hamichee","CHÈ HẠT ĐÁC SẦU RIÊNG HAMI",48000],
  ["che-hat-dac-cu-nang-hat-sen","che-quoc-dan-hamichee","CHÈ HẠT ĐÁC CỦ NĂNG HẠT SEN",42000],
  ["che-thai-sau-rieng-hami","che-quoc-dan-hamichee","CHÈ THÁI SẦU RIÊNG HAMI",42000,true],
  ["che-khoai-deo-hami","che-quoc-dan-hamichee","CHÈ KHOAI DẺO HAMI",42000,true],
  ["che-khuc-bach-hami","che-quoc-dan-hamichee","CHÈ KHÚC BẠCH HAMI",42000],
  ["che-dua-non-hat-dac","che-quoc-dan-hamichee","CHÈ DỪA NON HẠT ĐÁC",30000,true],
  ["che-khoai-tim-cot-dua","che-truyen-thong","CHÈ KHOAI TÍM CỐT DỪA",18000,true],
  ["che-bap","che-truyen-thong","CHÈ BẮP",18000],
  ["che-bat-ngo","che-truyen-thong","CHÈ BẤT NGỜ",22000],
  ["che-thap-cam","che-truyen-thong","CHÈ THẬP CẨM",30000],
  ["che-banh-lot-cu-nang-sau-rieng","che-ly","CHÈ BÁNH LỌT CỦ NĂNG SẦU RIÊNG",42000],
  ["che-suong-sao-hat-dac-cot-dua","che-ly","CHÈ SƯƠNG SÁO HẠT ĐÁC CỐT DỪA",30000],
  ["che-dau-den-hat-dac-cot-dua","che-ly","CHÈ ĐẬU ĐEN HẠT ĐÁC CỐT DỪA",30000],
  ["sua-chua-hat-dac-hamichee","sua-chua","SỮA CHUA HẠT ĐÁC HAMICHEE",40000],
  ["sua-chua-hat-dac-trai-cay","sua-chua","SỮA CHUA HẠT ĐÁC TRÁI CÂY",42000,true],
  ["tra-trai-cay-nhiet-doi","tuoi-mat","TRÀ TRÁI CÂY NHIỆT ĐỚI",40000,true],
  ["tra-dau-tam-hat-dac","tuoi-mat","TRÀ DÂU TẰM HẠT ĐÁC",35000,true],
  ["tra-da-me-hat-dac","tuoi-mat","TRÀ ĐÁ ME HẠT ĐÁC",35000],
  ["tra-mang-cau","tuoi-mat","TRÀ MÃNG CẦU",35000],
  ["nuoc-sam-full-topping","tuoi-mat","NƯỚC SÂM FULL TOPPING",25000,true],
  ["nuoc-dua-tac-trai-cay","tuoi-mat","NƯỚC DỪA TẮC TRÁI CÂY",25000,true],
  ["tra-long-nhan-hat-sen","tuoi-mat","TRÀ LONG NHÃN HẠT SEN",35000],
  ["flan-truyen-thong-2-banh","trung-nha","FLAN TRUYỀN THỐNG (2 Bánh)",20000],
  ["flan-hat-dac-hami","trung-nha","FLAN HẠT ĐÁC HAMI",30000],
  ["milo-da-bao-flan","trung-nha","MILO ĐÁ BÀO FLAN",35000,true],
  ["banh-trang-tron-hang-minh","an-chill-cung-che","BÁNH TRÁNG TRỘN HÀNG MINH",35000,true],
  ["banh-trang-cuon-bo-sot-me","an-chill-cung-che","BÁNH TRÁNG CUỘN BƠ SỐT ME",30000],
  ["combo-chien-nho","an-chill-cung-che","COMBO CHIÊN NHỎ",69000],
  ["combo-chien-lon","an-chill-cung-che","COMBO CHIÊN LỚN",99000],
  ["banh-gau-kem-sua","an-chill-cung-che","BÁNH GẤU KEM SỮA",25000],
  ["banh-que-cham-sot","an-chill-cung-che","BÁNH QUE CHẤM SỐT",25000],
  ["xuc-xich-duc","an-chill-cung-che","XÚC XÍCH ĐỨC",40000],
  ["khoai-tay-chien","an-chill-cung-che","KHOAI TÂY CHIÊN",35000],
  ["khoai-tay-lac-phomai","an-chill-cung-che","KHOAI TÂY LẮC PHOMAI",40000],
  ["ga-vien-lac-phomai","an-chill-cung-che","GÀ VIÊN LẮC PHOMAI",45000],
  ["chan-ga-rut-xuong-sot-thai","an-chill-cung-che","CHÂN GÀ RÚT XƯƠNG SỐT THÁI",55000],
  ["chan-ga-ngam-sa-tac","an-chill-cung-che","CHÂN GÀ NGÂM SẢ TẮC",55000],
  ["khuc-bach-hami","them-chut-ngon-hon","KHÚC BẠCH HAMI",10000],
  ["thach-cu-nang","them-chut-ngon-hon","THẠCH CỦ NĂNG",10000],
  ["thach-phomai","them-chut-ngon-hon","THẠCH PHOMAI",10000],
  ["hat-dac-rim","them-chut-ngon-hon","HẠT ĐÁC RIM",12000,true],
  ["suong-sao","them-chut-ngon-hon","SƯƠNG SÁO",8000],
  ["tran-chau-dua","them-chut-ngon-hon","TRÂN CHÂU DỪA",8000],
  ["thach-vi-nha","them-chut-ngon-hon","THẠCH VỊ NHÀ",8000],
  ["khoai-deo","them-chut-ngon-hon","KHOAI DẺO",10000],
  ["flan","them-chut-ngon-hon","FLAN",10000,true],
  ["trai-cay","them-chut-ngon-hon","TRÁI CÂY",10000],
  ["sot-khoai-socola","them-chut-ngon-hon","SỐT KHOAI (SOCOLA)",8000],
  ["dac-rim-thom-mat","the-gioi-hat-dac","ĐÁC RIM THƠM MẬT",85000,false,[{"label":"0,5kg","price":85000},{"label":"1kg","price":165000}]],
  ["dac-rim-chanh-day","the-gioi-hat-dac","ĐÁC RIM CHANH DÂY",85000,false,[{"label":"0,5kg","price":85000},{"label":"1kg","price":165000}]],
  ["dac-rim-dau-tam","the-gioi-hat-dac","ĐÁC RIM DÂU TẰM",85000,false,[{"label":"0,5kg","price":85000},{"label":"1kg","price":165000}]],
  ["dac-rim-gung-non","the-gioi-hat-dac","ĐÁC RIM GỪNG NON",85000,false,[{"label":"0,5kg","price":85000},{"label":"1kg","price":165000}]],
] as const;

export function fallbackMenu(): MenuCategory[] {
  return seedCategories.map(([id, name, image_position], index) => ({
    id,
    name,
    image_position,
    sort_order: index,
    active: true,
    products: seedProducts
      .filter((product) => product[1] === id)
      .map(([productId, categoryId, productName, price, featured = false, variants = []], productIndex): Product => ({
        id: productId,
        category_id: categoryId,
        name: productName,
        price,
        image_url: null,
        image_position,
        featured,
        active: true,
        variants: [...variants],
        sort_order: productIndex,
      })),
  }));
}
